import type { Prisma } from "../../generated/prisma/client.js"; import type { DatabaseClient } from "../auth/repo.js";
export const taskInclude = { createdBy: { select: { id: true, name: true } }, legalCase: { select: { id: true, title: true, caseNumber: true, status: true } }, subCase: { select: { id: true, title: true, status: true } }, assignments: { include: { user: { select: { id: true, name: true, email: true } }, assignedBy: { select: { id: true, name: true } } }, orderBy: { assignedAt: "desc" as const } }, history: { include: { changedBy: { select: { id: true, name: true } } }, orderBy: { changedAt: "desc" as const } }, comments: { where: { deletedAt: null }, include: { author: { select: { id: true, name: true } } }, orderBy: { createdAt: "asc" as const } }, _count: { select: { documents: true } } } satisfies Prisma.TaskInclude;
export type TaskRow = Prisma.TaskGetPayload<{ include: typeof taskInclude }>;
export class TaskRepository {
  list(db: DatabaseClient, f: { status?: Prisma.EnumTaskStatusFilter["equals"]; priority?: Prisma.EnumTaskPriorityFilter["equals"]; assigneeId?: string; caseId?: string; dueFrom?: Date; dueTo?: Date; cursor?: { updatedAt: string; id: string }; limit: number }) { const c = f.cursor ? { updatedAt: new Date(f.cursor.updatedAt), id: f.cursor.id } : null; return db.task.findMany({ where: { deletedAt: null, ...(f.status ? { status: f.status } : {}), ...(f.priority ? { priority: f.priority } : {}), ...(f.caseId ? { caseId: f.caseId } : {}), ...(f.assigneeId ? { assignments: { some: { userId: f.assigneeId, unassignedAt: null } } } : {}), ...((f.dueFrom || f.dueTo) ? { dueDate: { ...(f.dueFrom ? { gte: f.dueFrom } : {}), ...(f.dueTo ? { lte: f.dueTo } : {}) } } : {}), ...(c ? { OR: [{ updatedAt: { lt: c.updatedAt } }, { updatedAt: c.updatedAt, id: { lt: c.id } }] } : {}) }, include: taskInclude, orderBy: [{ updatedAt: "desc" }, { id: "desc" }], take: f.limit + 1 }); }
  find(db: DatabaseClient, id: string) { return db.task.findFirst({ where: { id, deletedAt: null }, include: taskInclude }); }
  create(db: DatabaseClient, data: Prisma.TaskUncheckedCreateInput, userIds: string[], actorId: string) { return db.task.create({ data: { ...data, assignments: { create: userIds.map((userId) => ({ userId, assignedById: actorId })) }, history: { create: { toStatus: data.status ?? "PENDING", changedById: actorId } } }, include: taskInclude }); }
  async update(db: DatabaseClient, id: string, version: number, data: Prisma.TaskUpdateManyMutationInput) { const result = await db.task.updateMany({ where: { id, version, deletedAt: null }, data: { ...data, version: { increment: 1 } } }); return result.count === 1 ? this.find(db, id) : null; }
  history(db: DatabaseClient, data: Prisma.TaskStatusHistoryUncheckedCreateInput) { return db.taskStatusHistory.create({ data }); }
  closeAssignments(db: DatabaseClient, taskId: string, except: string[]) { return db.taskAssignment.updateMany({ where: { taskId, unassignedAt: null, ...(except.length ? { userId: { notIn: except } } : {}) }, data: { unassignedAt: new Date() } }); }
  addAssignments(db: DatabaseClient, taskId: string, userIds: string[], actorId: string) { return db.taskAssignment.createMany({ data: userIds.map((userId) => ({ taskId, userId, assignedById: actorId })), skipDuplicates: true }); }
  comment(db: DatabaseClient, taskId: string, actorId: string, content: string) { return db.taskComment.create({ data: { taskId, authorId: actorId, content }, include: { author: { select: { id: true, name: true } } } }); }
  findComment(db: DatabaseClient, taskId: string, id: string) { return db.taskComment.findFirst({ where: { id, taskId, deletedAt: null }, include: { author: true } }); }
  async updateComment(db: DatabaseClient, id: string, version: number, content: string) { const result = await db.taskComment.updateMany({ where: { id, version, deletedAt: null }, data: { content, version: { increment: 1 } } }); return result.count; }
  deleteComment(db: DatabaseClient, id: string) { return db.taskComment.update({ where: { id }, data: { deletedAt: new Date(), version: { increment: 1 } } }); }
  users(db: DatabaseClient, ids: string[]) { return db.user.count({ where: { id: { in: ids }, status: "ACTIVE" } }); }
  case(db: DatabaseClient, id: string) { return db.legalCase.findFirst({ where: { id, deletedAt: null }, select: { id: true, status: true } }); }
  subcase(db: DatabaseClient, id: string) { return db.subCase.findFirst({ where: { id, deletedAt: null }, select: { id: true, caseId: true, status: true } }); }
}
export const taskRepository = new TaskRepository();
