import type { Prisma } from "../../generated/prisma/client.js";
import type { CaseStatus, CaseType, ParticipantRole, PartySide, RepresentationType } from "../../generated/prisma/enums.js";
import { getPrisma } from "../../database/prisma.js";
import { ApiError } from "../../shared/http/errors.js";
import { normalizeIdentifier, normalizeSearch } from "../../shared/validation/normalize.js";
import { auditService } from "../audit/service.js";
import type { AuthenticatedActor, RequestContext } from "../auth/types.js";
import { outboxService } from "../outbox/service.js";
import { decodeCaseCursor, encodeCaseCursor } from "./cursor.js";
import { toCaseDto } from "./mapper.js";
import { caseRepository } from "./repo.js";

type ParticipantInput = { contactId: string; role: ParticipantRole; side: PartySide; isClient: boolean; label?: string | null | undefined; notes?: string | null | undefined; sortOrder: number };
type TeamInput = { userId: string; role: "PRIMARY" | "COLLABORATOR" };
type RepresentationInput = { representedContactId: string; representativeContactId: string; type: RepresentationType; isPrimary: boolean; notes?: string | null | undefined };
type CreateInput = { caseNumber: string; title: string; type: CaseType; status: "PENDING" | "ACTIVE"; startDate: Date; courtId?: string | null | undefined; managementOfficeId?: string | null | undefined; courtName?: string | null | undefined; managementOfficeName?: string | null | undefined; participants: ParticipantInput[]; representations: RepresentationInput[]; team: TeamInput[] };

const metadata = (context: RequestContext) => ({ ...(context.requestId ? { requestId: context.requestId } : {}), ...(context.ipAddress ? { ipAddress: context.ipAddress } : {}), ...(context.userAgent ? { userAgent: context.userAgent } : {}) });
const today = () => { const now = new Date(); return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())); };
const needsReason = (from: CaseStatus, to: CaseStatus) => (from === "PENDING" && to === "CLOSED") || (from === "ACTIVE" && ["SUSPENDED", "CLOSED"].includes(to)) || (from === "SUSPENDED") || (from === "CLOSED" && to === "ACTIVE") || (from === "ARCHIVED");
const transitions: Record<CaseStatus, CaseStatus[]> = { PENDING: ["ACTIVE", "CLOSED"], ACTIVE: ["SUSPENDED", "CLOSED"], SUSPENDED: ["ACTIVE", "CLOSED"], CLOSED: ["ACTIVE", "ARCHIVED"], ARCHIVED: ["CLOSED", "ACTIVE"] };

export class CaseService {
  async list(input: { q?: string | undefined; status?: CaseStatus | undefined; type?: CaseType | undefined; responsibleId?: string | undefined; courtId?: string | undefined; from?: Date | undefined; to?: Date | undefined; cursor?: string | undefined; limit: number }) {
    const cursor = decodeCaseCursor(input.cursor);
    const rows = await caseRepository.list(getPrisma(), { ...(input.q ? { q: normalizeSearch(input.q) } : {}), ...(input.status ? { status: input.status } : {}), ...(input.type ? { type: input.type } : {}), ...(input.responsibleId ? { responsibleId: input.responsibleId } : {}), ...(input.courtId ? { courtId: input.courtId } : {}), ...(input.from ? { from: input.from } : {}), ...(input.to ? { to: input.to } : {}), ...(cursor ? { cursor } : {}), limit: input.limit });
    const hasMore = rows.length > input.limit; const selected = hasMore ? rows.slice(0, input.limit) : rows; const last = selected.at(-1);
    return { data: selected.map(toCaseDto), meta: { nextCursor: hasMore && last ? encodeCaseCursor({ updatedAt: last.updatedAt.toISOString(), id: last.id }) : null } };
  }

  async get(id: string) { const value = await caseRepository.findById(getPrisma(), id); if (!value) throw new ApiError("NOT_FOUND", "Expediente no encontrado."); return toCaseDto(value); }

  async create(input: CreateInput, actor: AuthenticatedActor, context: RequestContext) {
    const prisma = getPrisma();
    if (!actor.user.permissions.includes("cases.assign")) throw new ApiError("FORBIDDEN", "El alta requiere permiso para asignar el equipo.");
    const primary = input.team.find((item) => item.role === "PRIMARY");
    if (!actor.user.permissions.includes("cases.archive") && primary?.userId !== actor.user.id) throw new ApiError("FORBIDDEN", "Sólo puede asignarse a sí mismo como responsable inicial.");
    return prisma.$transaction(async (transaction) => {
      await this.validateReferences(transaction, input);
      const legalCase = await caseRepository.create(transaction, { caseNumber: input.caseNumber, caseNumberNormalized: normalizeIdentifier(input.caseNumber), title: input.title, type: input.type, status: input.status, startDate: input.startDate, courtId: input.courtId ?? null, managementOfficeId: input.managementOfficeId ?? null, courtName: input.courtName ?? null, managementOfficeName: input.managementOfficeName ?? null, createdById: actor.user.id });
      const participants = [];
      for (const item of input.participants) participants.push(await caseRepository.createParticipant(transaction, { caseId: legalCase.id, contactId: item.contactId, role: item.role, side: item.side, isClient: item.isClient, sortOrder: item.sortOrder, ...(item.label !== undefined ? { label: item.label } : {}), ...(item.notes !== undefined ? { notes: item.notes } : {}) }));
      for (const item of input.representations) {
        const candidates = participants.filter((participant) => participant.contactId === item.representedContactId);
        if (candidates.length !== 1) throw new ApiError("VALIDATION_ERROR", "La parte representada debe identificar una única participación.");
        if (item.isPrimary) await caseRepository.unsetPrimaryRepresentations(transaction, candidates[0]!.id);
        await caseRepository.createRepresentation(transaction, { caseId: legalCase.id, representedParticipantId: candidates[0]!.id, representativeContactId: item.representativeContactId, type: item.type, isPrimary: item.isPrimary, ...(item.notes !== undefined ? { notes: item.notes } : {}) });
      }
      for (const item of input.team) await caseRepository.createTeamMember(transaction, { caseId: legalCase.id, userId: item.userId, role: item.role, assignedById: actor.user.id });
      await caseRepository.addStatusHistory(transaction, { caseId: legalCase.id, toStatus: input.status, changedById: actor.user.id });
      await auditService.record(transaction, { actorId: actor.user.id, action: "CASE_CREATED", entityType: "LegalCase", entityId: legalCase.id, after: { caseNumber: legalCase.caseNumber, status: legalCase.status }, ...metadata(context) });
      await outboxService.publish(transaction, { type: "CASE_CREATED", aggregateType: "LegalCase", aggregateId: legalCase.id, payload: { caseId: legalCase.id } });
      const result = await caseRepository.findById(transaction, legalCase.id); if (!result) throw new ApiError("NOT_FOUND", "Expediente no encontrado."); return toCaseDto(result);
    });
  }

  async update(id: string, input: { version: number; caseNumber?: string | undefined; title?: string | undefined; type?: CaseType | undefined; startDate?: Date | undefined; courtId?: string | null | undefined; managementOfficeId?: string | null | undefined; courtName?: string | null | undefined; managementOfficeName?: string | null | undefined }, actor: AuthenticatedActor, context: RequestContext) {
    const prisma = getPrisma(); const current = await caseRepository.findById(prisma, id); if (!current) throw new ApiError("NOT_FOUND", "Expediente no encontrado."); if (current.status === "ARCHIVED") throw new ApiError("CONFLICT", "Un expediente archivado es de sólo lectura.");
    const courtId = input.courtId !== undefined ? input.courtId : current.courtId; const officeId = input.managementOfficeId !== undefined ? input.managementOfficeId : current.managementOfficeId;
    return prisma.$transaction(async (transaction) => {
      await this.validateLocation(transaction, courtId, officeId);
      const updated = await caseRepository.update(transaction, id, input.version, { ...(input.caseNumber !== undefined ? { caseNumber: input.caseNumber, caseNumberNormalized: normalizeIdentifier(input.caseNumber) } : {}), ...(input.title !== undefined ? { title: input.title } : {}), ...(input.type !== undefined ? { type: input.type } : {}), ...(input.startDate !== undefined ? { startDate: input.startDate } : {}), ...(input.courtId !== undefined ? { courtId: input.courtId } : {}), ...(input.managementOfficeId !== undefined ? { managementOfficeId: input.managementOfficeId } : {}), ...(input.courtName !== undefined ? { courtName: input.courtName } : {}), ...(input.managementOfficeName !== undefined ? { managementOfficeName: input.managementOfficeName } : {}) });
      if (!updated) throw new ApiError("CONFLICT", "El expediente fue modificado por otra operación.");
      await auditService.record(transaction, { actorId: actor.user.id, action: "CASE_UPDATED", entityType: "LegalCase", entityId: id, before: { version: current.version }, after: { version: updated.version }, ...metadata(context) });
      await outboxService.publish(transaction, { type: "CASE_UPDATED", aggregateType: "LegalCase", aggregateId: id, payload: { caseId: id, version: updated.version } }); return toCaseDto(updated);
    });
  }

  async transition(id: string, input: { version: number; toStatus: CaseStatus; reason?: string | null | undefined; openTaskStrategy?: "KEEP" | undefined }, actor: AuthenticatedActor, context: RequestContext) {
    const prisma = getPrisma(); const current = await caseRepository.findById(prisma, id); if (!current) throw new ApiError("NOT_FOUND", "Expediente no encontrado.");
    if (!transitions[current.status].includes(input.toStatus)) throw new ApiError("CONFLICT", `Transición no permitida: ${current.status} → ${input.toStatus}.`);
    if (needsReason(current.status, input.toStatus) && !input.reason) throw new ApiError("VALIDATION_ERROR", "El motivo es obligatorio para esta transición.");
    if ((current.status === "CLOSED" || current.status === "ARCHIVED" || input.toStatus === "ARCHIVED") && !actor.user.permissions.includes("cases.archive")) throw new ApiError("FORBIDDEN", "La reapertura o el archivo requiere permiso administrativo.");
    if (input.toStatus === "CLOSED" && today() < current.startDate) throw new ApiError("VALIDATION_ERROR", "No se puede cerrar antes de la fecha de inicio.");
    const openTasks = input.toStatus === "CLOSED" ? await caseRepository.countOpenTasks(prisma, id) : 0;
    if (openTasks > 0 && input.openTaskStrategy !== "KEEP") throw new ApiError("CONFLICT", `El expediente tiene ${openTasks} tareas abiertas; indique la estrategia KEEP.`);
    return prisma.$transaction(async (transaction) => {
      const date = today(); const updated = await caseRepository.update(transaction, id, input.version, { status: input.toStatus, ...(input.toStatus === "CLOSED" ? { closedOn: date, archivedOn: null } : {}), ...(input.toStatus === "ARCHIVED" ? { archivedOn: date } : {}), ...(["ACTIVE", "PENDING", "SUSPENDED"].includes(input.toStatus) ? { closedOn: null, archivedOn: null } : {}), ...(input.toStatus === "CLOSED" && current.status === "ARCHIVED" ? { archivedOn: null } : {}) });
      if (!updated) throw new ApiError("CONFLICT", "El expediente fue modificado por otra operación.");
      await caseRepository.addStatusHistory(transaction, { caseId: id, fromStatus: current.status, toStatus: input.toStatus, changedById: actor.user.id, ...(input.reason !== undefined ? { reason: input.reason } : {}) });
      await auditService.record(transaction, { actorId: actor.user.id, action: "CASE_STATUS_CHANGED", entityType: "LegalCase", entityId: id, before: { status: current.status, version: current.version }, after: { status: input.toStatus, version: updated.version }, ...metadata(context) });
      await outboxService.publish(transaction, { type: "CASE_STATUS_CHANGED", aggregateType: "LegalCase", aggregateId: id, payload: { caseId: id, fromStatus: current.status, toStatus: input.toStatus } }); return toCaseDto(updated);
    });
  }

  async remove(id: string, actor: AuthenticatedActor, context: RequestContext) { const prisma = getPrisma(); const current = await caseRepository.findById(prisma, id); if (!current) throw new ApiError("NOT_FOUND", "Expediente no encontrado."); const count = current._count; if (count.actions + count.subCases + count.tasks + count.documents + count.notes > 0) throw new ApiError("CONFLICT", "Sólo puede darse de baja un alta errónea sin actividad relacionada."); await prisma.$transaction(async (transaction) => { await caseRepository.softDelete(transaction, id); await auditService.record(transaction, { actorId: actor.user.id, action: "CASE_DELETED", entityType: "LegalCase", entityId: id, before: { caseNumber: current.caseNumber }, ...metadata(context) }); await outboxService.publish(transaction, { type: "CASE_DELETED", aggregateType: "LegalCase", aggregateId: id, payload: { caseId: id } }); }); }

  async addParticipant(caseId: string, input: ParticipantInput, actor: AuthenticatedActor, context: RequestContext) { return this.mutate(caseId, actor, context, "CASE_PARTICIPANT_ADDED", async (tx) => { if (await caseRepository.countContacts(tx, [input.contactId]) !== 1) throw new ApiError("VALIDATION_ERROR", "El contacto no existe o está inactivo."); await caseRepository.createParticipant(tx, { caseId, contactId: input.contactId, role: input.role, side: input.side, isClient: input.isClient, sortOrder: input.sortOrder, ...(input.label !== undefined ? { label: input.label } : {}), ...(input.notes !== undefined ? { notes: input.notes } : {}) }); }); }
  async updateParticipant(caseId: string, participantId: string, input: { role?: ParticipantRole | undefined; side?: PartySide | undefined; isClient?: boolean | undefined; label?: string | null | undefined; notes?: string | null | undefined; sortOrder?: number | undefined }, actor: AuthenticatedActor, context: RequestContext) { const current = await caseRepository.findParticipant(getPrisma(), caseId, participantId); if (!current) throw new ApiError("NOT_FOUND", "Parte no encontrada."); if (current.isClient && input.isClient === false && await caseRepository.countActiveClients(getPrisma(), caseId) <= 1) throw new ApiError("CONFLICT", "El expediente debe conservar al menos una parte cliente."); const role = input.role ?? current.role; const label = input.label !== undefined ? input.label : current.label; if (role === "OTHER" && !label) throw new ApiError("VALIDATION_ERROR", "La etiqueta es obligatoria para el rol Otro."); return this.mutate(caseId, actor, context, "CASE_PARTICIPANT_UPDATED", async (tx) => { await caseRepository.updateParticipant(tx, participantId, { ...(input.role !== undefined ? { role: input.role } : {}), ...(input.side !== undefined ? { side: input.side } : {}), ...(input.isClient !== undefined ? { isClient: input.isClient } : {}), ...(input.label !== undefined ? { label: input.label } : {}), ...(input.notes !== undefined ? { notes: input.notes } : {}), ...(input.sortOrder !== undefined ? { sortOrder: input.sortOrder } : {}) }); }); }
  async removeParticipant(caseId: string, participantId: string, actor: AuthenticatedActor, context: RequestContext) { const current = await caseRepository.findParticipant(getPrisma(), caseId, participantId); if (!current) throw new ApiError("NOT_FOUND", "Parte no encontrada."); if (current.isClient && await caseRepository.countActiveClients(getPrisma(), caseId) <= 1) throw new ApiError("CONFLICT", "El expediente debe conservar al menos una parte cliente."); return this.mutate(caseId, actor, context, "CASE_PARTICIPANT_REMOVED", async (tx) => { await caseRepository.updateParticipant(tx, participantId, { activeUntil: today(), isClient: false }); }); }
  async addRepresentation(caseId: string, participantId: string, input: { representativeContactId: string; type: RepresentationType; isPrimary: boolean; notes?: string | null | undefined }, actor: AuthenticatedActor, context: RequestContext) { if (!(await caseRepository.findParticipant(getPrisma(), caseId, participantId))) throw new ApiError("NOT_FOUND", "Parte no encontrada."); return this.mutate(caseId, actor, context, "CASE_REPRESENTATION_ADDED", async (tx) => { if (await caseRepository.countContacts(tx, [input.representativeContactId]) !== 1) throw new ApiError("VALIDATION_ERROR", "El representante no existe o está inactivo."); if (input.isPrimary) await caseRepository.unsetPrimaryRepresentations(tx, participantId); await caseRepository.createRepresentation(tx, { caseId, representedParticipantId: participantId, representativeContactId: input.representativeContactId, type: input.type, isPrimary: input.isPrimary, ...(input.notes !== undefined ? { notes: input.notes } : {}) }); }); }
  async removeRepresentation(caseId: string, representationId: string, actor: AuthenticatedActor, context: RequestContext) { if (!(await caseRepository.findRepresentation(getPrisma(), caseId, representationId))) throw new ApiError("NOT_FOUND", "Representación no encontrada."); return this.mutate(caseId, actor, context, "CASE_REPRESENTATION_REMOVED", async (tx) => { await caseRepository.endRepresentation(tx, representationId, today()); }); }

  async addTeam(caseId: string, input: TeamInput, actor: AuthenticatedActor, context: RequestContext) { this.assertAssignment(actor, input.userId, input.role); return this.mutate(caseId, actor, context, "CASE_TEAM_ASSIGNED", async (tx) => { if (await caseRepository.countActiveUsers(tx, [input.userId]) !== 1) throw new ApiError("VALIDATION_ERROR", "El usuario no existe o está inactivo."); if (input.role === "PRIMARY") await caseRepository.unassignPrimary(tx, caseId, new Date()); await caseRepository.createTeamMember(tx, { caseId, userId: input.userId, role: input.role, assignedById: actor.user.id }); }); }
  async updateTeam(caseId: string, membershipId: string, input: { role?: "PRIMARY" | "COLLABORATOR" | undefined; unassign?: boolean | undefined }, actor: AuthenticatedActor, context: RequestContext) { const current = await caseRepository.findTeamMember(getPrisma(), caseId, membershipId); if (!current) throw new ApiError("NOT_FOUND", "Asignación no encontrada."); this.assertAssignment(actor, current.userId, input.role ?? current.role); if ((input.unassign || input.role === "COLLABORATOR") && current.role === "PRIMARY") throw new ApiError("CONFLICT", "Asigne otro responsable principal antes de finalizar o degradar esta asignación."); return this.mutate(caseId, actor, context, "CASE_TEAM_UPDATED", async (tx) => { if (input.role === "PRIMARY") await caseRepository.unassignPrimary(tx, caseId, new Date(), membershipId); await caseRepository.updateTeamMember(tx, membershipId, { ...(input.role ? { role: input.role } : {}), ...(input.unassign ? { unassignedAt: new Date() } : {}) }); }); }

  async history(id: string) { const value = await this.get(id); return value.statusHistory; }
  async summary(id: string) { const value = await this.get(id); return value.summary; }
  async timeline(id: string) { const value = await this.get(id); return value.statusHistory.map((item) => ({ id: item.id, kind: "STATUS", at: item.changedAt, title: `${item.fromStatus ?? "CREATED"} → ${item.toStatus}`, detail: item.reason, actor: item.changedBy })); }
  async forContact(contactId: string) { return (await caseRepository.listForContact(getPrisma(), contactId)).map(toCaseDto); }

  private async mutate(caseId: string, actor: AuthenticatedActor, context: RequestContext, action: string, operation: (tx: Prisma.TransactionClient) => Promise<void>) { const prisma = getPrisma(); const current = await caseRepository.findById(prisma, caseId); if (!current) throw new ApiError("NOT_FOUND", "Expediente no encontrado."); if (current.status === "ARCHIVED") throw new ApiError("CONFLICT", "Un expediente archivado es de sólo lectura."); return prisma.$transaction(async (transaction) => { await operation(transaction); await auditService.record(transaction, { actorId: actor.user.id, action, entityType: "LegalCase", entityId: caseId, ...metadata(context) }); await outboxService.publish(transaction, { type: action, aggregateType: "LegalCase", aggregateId: caseId, payload: { caseId } }); const result = await caseRepository.findById(transaction, caseId); if (!result) throw new ApiError("NOT_FOUND", "Expediente no encontrado."); return toCaseDto(result); }); }
  private assertAssignment(actor: AuthenticatedActor, userId: string, role: "PRIMARY" | "COLLABORATOR") { if (!actor.user.permissions.includes("cases.archive") && (userId !== actor.user.id || role !== "COLLABORATOR")) throw new ApiError("FORBIDDEN", "Sólo puede administrarse como colaborador propio."); }
  private async validateLocation(transaction: Prisma.TransactionClient, courtId: string | null, officeId: string | null) { if (courtId && !(await caseRepository.findCourt(transaction, courtId))) throw new ApiError("VALIDATION_ERROR", "El juzgado no existe o está inactivo."); if (officeId && !(await caseRepository.findOffice(transaction, officeId))) throw new ApiError("VALIDATION_ERROR", "La oficina no existe o está inactiva."); if (courtId && officeId && await caseRepository.courtOfficeExists(transaction, courtId, officeId) !== 1) throw new ApiError("VALIDATION_ERROR", "La oficina no pertenece al juzgado seleccionado."); }
  private async validateReferences(transaction: Prisma.TransactionClient, input: CreateInput) { await this.validateLocation(transaction, input.courtId ?? null, input.managementOfficeId ?? null); const contactIds = [...new Set([...input.participants.map((item) => item.contactId), ...input.representations.map((item) => item.representativeContactId)])]; if (await caseRepository.countContacts(transaction, contactIds) !== contactIds.length) throw new ApiError("VALIDATION_ERROR", "Una o más personas de la causa no existen o están inactivas."); const userIds = [...new Set(input.team.map((item) => item.userId))]; if (await caseRepository.countActiveUsers(transaction, userIds) !== userIds.length) throw new ApiError("VALIDATION_ERROR", "Uno o más integrantes del equipo no existen o están inactivos."); }
}
export const caseService = new CaseService();
