import type { Prisma } from "../../generated/prisma/client.js";
import type { SubCaseStatus, SubCaseType } from "../../generated/prisma/enums.js";
import { getPrisma } from "../../database/prisma.js";
import { ApiError } from "../../shared/http/errors.js";
import { auditService } from "../audit/service.js";
import type { AuthenticatedActor, RequestContext } from "../auth/types.js";
import { caseRepository } from "../cases/repo.js";
import { outboxService } from "../outbox/service.js";
import { toSubCaseDto } from "./mapper.js";
import { subCaseRepository } from "./repo.js";
const metadata = (context: RequestContext) => ({ ...(context.requestId ? { requestId: context.requestId } : {}), ...(context.ipAddress ? { ipAddress: context.ipAddress } : {}), ...(context.userAgent ? { userAgent: context.userAgent } : {}) });
const transitions: Record<SubCaseStatus, SubCaseStatus[]> = { ACTIVE: ["RESOLVED", "CLOSED"], RESOLVED: ["ACTIVE", "CLOSED"], CLOSED: ["ACTIVE"] };
const reasonRequired = (from: SubCaseStatus, to: SubCaseStatus) => (from === "ACTIVE" && ["RESOLVED", "CLOSED"].includes(to)) || (to === "ACTIVE");
export class SubCaseService {
  async list(caseId: string, filters: { type?: SubCaseType | undefined; status?: SubCaseStatus | undefined }) { await this.case(caseId); return (await subCaseRepository.list(getPrisma(), caseId, { ...(filters.type ? { type: filters.type } : {}), ...(filters.status ? { status: filters.status } : {}) })).map(toSubCaseDto); }
  async get(id: string) { const value = await subCaseRepository.find(getPrisma(), id); if (!value) throw new ApiError("NOT_FOUND", "Cuaderno no encontrado."); return toSubCaseDto(value); }
  async create(caseId: string, input: { type: SubCaseType; title: string; description?: string | null | undefined; openedOn?: Date | undefined }, actor: AuthenticatedActor, context: RequestContext) { const prisma = getPrisma(); const legalCase = await this.case(caseId); if (legalCase.status === "ARCHIVED") throw new ApiError("CONFLICT", "El expediente archivado es de sólo lectura."); return prisma.$transaction(async (tx) => { const value = await subCaseRepository.create(tx, { caseId, type: input.type, title: input.title, openedOn: input.openedOn ?? new Date(), createdById: actor.user.id, ...(input.description !== undefined ? { description: input.description } : {}) }); await this.record(tx, actor, context, "SUBCASE_CREATED", value.id, caseId, { status: value.status }); return toSubCaseDto(value); }); }
  async update(id: string, input: { version: number; title?: string | undefined; description?: string | null | undefined }, actor: AuthenticatedActor, context: RequestContext) { const current = await subCaseRepository.find(getPrisma(), id); if (!current) throw new ApiError("NOT_FOUND", "Cuaderno no encontrado."); await this.mutableCase(current.caseId); if (current.status === "CLOSED") throw new ApiError("CONFLICT", "El cuaderno cerrado es de sólo lectura."); return getPrisma().$transaction(async (tx) => { const value = await subCaseRepository.update(tx, id, input.version, { ...(input.title !== undefined ? { title: input.title } : {}), ...(input.description !== undefined ? { description: input.description } : {}) }); if (!value) throw new ApiError("CONFLICT", "El cuaderno fue modificado por otra operación."); await this.record(tx, actor, context, "SUBCASE_UPDATED", id, current.caseId, { version: value.version }); return toSubCaseDto(value); }); }
  async transition(id: string, input: { version: number; toStatus: SubCaseStatus; reason?: string | null | undefined }, actor: AuthenticatedActor, context: RequestContext) { const current = await subCaseRepository.find(getPrisma(), id); if (!current) throw new ApiError("NOT_FOUND", "Cuaderno no encontrado."); await this.mutableCase(current.caseId); if (!transitions[current.status].includes(input.toStatus)) throw new ApiError("CONFLICT", `Transición no permitida: ${current.status} → ${input.toStatus}.`); if (reasonRequired(current.status, input.toStatus) && !input.reason) throw new ApiError("VALIDATION_ERROR", "El motivo es obligatorio."); if (current.status === "CLOSED" && !actor.user.permissions.includes("cases.archive")) throw new ApiError("FORBIDDEN", "Reabrir un cuaderno cerrado requiere permiso administrativo."); return getPrisma().$transaction(async (tx) => { const value = await subCaseRepository.update(tx, id, input.version, { status: input.toStatus, closedOn: input.toStatus === "CLOSED" ? new Date() : null }); if (!value) throw new ApiError("CONFLICT", "El cuaderno fue modificado por otra operación."); await this.record(tx, actor, context, "SUBCASE_STATUS_CHANGED", id, current.caseId, { fromStatus: current.status, toStatus: input.toStatus, reason: input.reason ?? null }); return toSubCaseDto(value); }); }
  async remove(id: string, actor: AuthenticatedActor, context: RequestContext) { const current = await subCaseRepository.find(getPrisma(), id); if (!current) throw new ApiError("NOT_FOUND", "Cuaderno no encontrado."); await this.mutableCase(current.caseId); if (Object.values(current._count).some((count) => count > 0)) throw new ApiError("CONFLICT", "No puede darse de baja un cuaderno con actividad relacionada."); await getPrisma().$transaction(async (tx) => { await subCaseRepository.softDelete(tx, id); await this.record(tx, actor, context, "SUBCASE_DELETED", id, current.caseId, { title: current.title }); }); }
  private async case(id: string) { const value = await caseRepository.findById(getPrisma(), id); if (!value) throw new ApiError("NOT_FOUND", "Expediente no encontrado."); return value; }
  private async mutableCase(id: string) { const value = await this.case(id); if (value.status === "ARCHIVED") throw new ApiError("CONFLICT", "El expediente archivado es de sólo lectura."); return value; }
  private async record(tx: Prisma.TransactionClient, actor: AuthenticatedActor, context: RequestContext, action: string, id: string, caseId: string, after: Prisma.InputJsonValue) { await auditService.record(tx, { actorId: actor.user.id, action, entityType: "SubCase", entityId: id, after, ...metadata(context) }); await outboxService.publish(tx, { type: action, aggregateType: "SubCase", aggregateId: id, payload: { subCaseId: id, caseId } }); }
}
export const subCaseService = new SubCaseService();
