import type { Prisma } from "../../generated/prisma/client.js"; import { getPrisma } from "../../database/prisma.js"; import { ApiError } from "../../shared/http/errors.js"; import { auditService } from "../audit/service.js"; import type { AuthenticatedActor, RequestContext } from "../auth/types.js"; import { notificationRepository } from "./repo.js";
const dto = (value: { id: string; type: string; title: string; body: string | null; entityType: string | null; entityId: string | null; readAt: Date | null; createdAt: Date }) => ({ id: value.id, type: value.type, title: value.title, body: value.body, entityType: value.entityType, entityId: value.entityId, readAt: value.readAt, createdAt: value.createdAt });
const decode = (value?: string) => { if (!value) return undefined; try { const parsed = JSON.parse(Buffer.from(value, "base64url").toString()) as { at?: unknown; id?: unknown }; const at = new Date(String(parsed.at)); if (typeof parsed.id !== "string" || Number.isNaN(at.getTime())) throw new Error(); return { at, id: parsed.id }; } catch { throw new ApiError("VALIDATION_ERROR", "Cursor inválido."); } };
export class NotificationService {
  async list(userId: string, input: { unread?: boolean | undefined; cursor?: string | undefined; limit: number }) { const rows = await notificationRepository.list(getPrisma(), { userId, unread: input.unread, cursor: decode(input.cursor), limit: input.limit }); const more = rows.length > input.limit; const selected = more ? rows.slice(0, input.limit) : rows; const last = selected.at(-1); return { data: selected.map(dto), meta: { nextCursor: more && last ? Buffer.from(JSON.stringify({ at: last.createdAt.toISOString(), id: last.id })).toString("base64url") : null, unreadCount: await notificationRepository.unreadCount(getPrisma(), userId) } }; }
  async read(id: string, userId: string) { if ((await notificationRepository.read(getPrisma(), id, userId)).count === 0) { const own = await getPrisma().notification.findFirst({ where: { id, userId } }); if (!own) throw new ApiError("NOT_FOUND", "Notificación no encontrada."); } }
  readAll(userId: string) { return notificationRepository.readAll(getPrisma(), userId); }
  async preference(userId: string) { return (await notificationRepository.preference(getPrisma(), userId)) ?? { userId, taskAssigned: true, taskDueSoon: true, taskOverdue: true, caseStatusChanged: true, emailEnabled: false, dueSoonLeadDays: 1 }; }
  async savePreference(input: { taskAssigned?: boolean | undefined; taskDueSoon?: boolean | undefined; taskOverdue?: boolean | undefined; caseStatusChanged?: boolean | undefined; emailEnabled?: boolean | undefined; dueSoonLeadDays?: number | undefined }, actor: AuthenticatedActor, context: RequestContext) { const data: Prisma.NotificationPreferenceUncheckedUpdateInput = { ...(input.taskAssigned !== undefined ? { taskAssigned: input.taskAssigned } : {}), ...(input.taskDueSoon !== undefined ? { taskDueSoon: input.taskDueSoon } : {}), ...(input.taskOverdue !== undefined ? { taskOverdue: input.taskOverdue } : {}), ...(input.caseStatusChanged !== undefined ? { caseStatusChanged: input.caseStatusChanged } : {}), ...(input.emailEnabled !== undefined ? { emailEnabled: input.emailEnabled } : {}), ...(input.dueSoonLeadDays !== undefined ? { dueSoonLeadDays: input.dueSoonLeadDays } : {}) }; return getPrisma().$transaction(async (tx) => { const value = await notificationRepository.savePreference(tx, actor.user.id, data); await auditService.record(tx, { actorId: actor.user.id, action: "NOTIFICATION_PREFERENCES_UPDATED", entityType: "NotificationPreference", entityId: value.id, after: input as Prisma.InputJsonValue, ...(context.requestId ? { requestId: context.requestId } : {}) }); return value; }); }
}
export const notificationService = new NotificationService();
