import request from "supertest";
import { afterAll, beforeEach, describe, expect, it } from "vitest";
import { buildApp } from "../../src/app.js"; import { disconnectDatabase } from "../../src/database/prisma.js"; import { passwordService } from "../../src/modules/auth/password.service.js"; import { createSyntheticCase } from "../fixtures/cases.js"; import { resetTestDatabase, testPrisma } from "../helpers/database.js";
const ORIGIN = "http://localhost:3000"; const PASSWORD = "ClaveSegura123"; const permissions = ["cases.read", "cases.archive", "subcases.manage", "actions.read", "actions.create", "actions.update", "actions.delete"];
async function auth(codes = permissions) { const items = await Promise.all(codes.map((code) => testPrisma.permission.create({ data: { code, description: code } }))); const role = await testPrisma.role.create({ data: { code: "PHASE7", name: "Phase 7", permissions: { create: items.map(({ id }) => ({ permissionId: id })) } } }); const user = await testPrisma.user.create({ data: { email: "phase7@example.com", emailNormalized: "phase7@example.com", name: "Phase Seven", passwordHash: await passwordService.hash(PASSWORD), roleId: role.id } }); const response = await request(buildApp()).post("/api/v1/auth/login").set("Origin", ORIGIN).send({ email: user.email, password: PASSWORD }); const cookies = response.headers["set-cookie"] as unknown as string[]; return { user, cookie: cookies[0]!.split(";")[0]!, csrf: response.body.data.csrfToken as string }; }
const headers = (value: { cookie: string; csrf: string }) => ({ Origin: ORIGIN, Cookie: value.cookie, "x-csrf-token": value.csrf });
beforeEach(async () => resetTestDatabase()); afterAll(async () => { await testPrisma.$disconnect(); await disconnectDatabase(); });
describe("subcases, actions and timeline", () => {
  it("creates a subcase and a valid action with audit/outbox", async () => { const logged = await auth(); const legalCase = await createSyntheticCase(testPrisma, logged.user); const app = buildApp(); const subcase = await request(app).post(`/api/v1/cases/${legalCase.id}/subcases`).set(headers(logged)).send({ type: "EVIDENCE", title: "Prueba documental" }); expect(subcase.status).toBe(201); const action = await request(app).post(`/api/v1/cases/${legalCase.id}/actions`).set(headers(logged)).send({ subCaseId: subcase.body.data.id, type: "FILING", title: "Ofrecimiento de prueba", documentAt: "2026-02-01T10:00:00.000Z" }); expect(action.status).toBe(201); expect(action.body.data.subCase.title).toBe("Prueba documental"); expect(await testPrisma.auditLog.count({ where: { action: { in: ["SUBCASE_CREATED", "ACTION_CREATED"] } } })).toBe(2); expect(await testPrisma.outboxEvent.count({ where: { type: { in: ["SUBCASE_CREATED", "ACTION_CREATED"] } } })).toBe(2); });
  it("rejects mixing a subcase from another case and rolls the action back", async () => { const logged = await auth(); const first = await createSyntheticCase(testPrisma, logged.user); const second = await createSyntheticCase(testPrisma, logged.user); const foreign = await testPrisma.subCase.create({ data: { caseId: second.id, type: "INCIDENT", title: "Ajeno", createdById: logged.user.id } }); const response = await request(buildApp()).post(`/api/v1/cases/${first.id}/actions`).set(headers(logged)).send({ subCaseId: foreign.id, type: "OTHER", title: "Inválida", documentAt: "2026-02-01T10:00:00.000Z" }); expect(response.status).toBe(400); expect(await testPrisma.caseAction.count()).toBe(0); });
  it("closes a subcase with optimistic locking, records the event and rejects later actions", async () => { const logged = await auth(); const legalCase = await createSyntheticCase(testPrisma, logged.user); const subcase = await testPrisma.subCase.create({ data: { caseId: legalCase.id, type: "INCIDENT", title: "Incidente", createdById: logged.user.id } }); const app = buildApp(); expect((await request(app).post(`/api/v1/subcases/${subcase.id}/status-transitions`).set(headers(logged)).send({ version: 1, toStatus: "CLOSED" })).status).toBe(400); const closed = await request(app).post(`/api/v1/subcases/${subcase.id}/status-transitions`).set(headers(logged)).send({ version: 1, toStatus: "CLOSED", reason: "Finalizado" }); expect(closed.status).toBe(200); expect((await request(app).post(`/api/v1/subcases/${subcase.id}/status-transitions`).set(headers(logged)).send({ version: 1, toStatus: "ACTIVE", reason: "Tardío" })).status).toBe(409); expect((await request(app).post(`/api/v1/cases/${legalCase.id}/actions`).set(headers(logged)).send({ subCaseId: subcase.id, type: "OTHER", title: "Posterior", documentAt: "2026-02-01T10:00:00.000Z" })).status).toBe(409); const timeline = await request(app).get(`/api/v1/cases/${legalCase.id}/timeline`).set("Cookie", logged.cookie); expect(timeline.body.data).toEqual(expect.arrayContaining([expect.objectContaining({ kind: "SUBCASE", title: "Incidente: ACTIVE → CLOSED", detail: "Finalizado" })])); });
  it("paginates the unified timeline stably when timestamps tie", async () => { const logged = await auth(); const legalCase = await createSyntheticCase(testPrisma, logged.user); const at = new Date("2026-04-05T12:00:00.000Z"); for (const title of ["Uno", "Dos", "Tres"]) await testPrisma.caseAction.create({ data: { caseId: legalCase.id, title, type: "OTHER", documentAt: at, uploadedById: logged.user.id } }); const app = buildApp(); const first = await request(app).get(`/api/v1/cases/${legalCase.id}/timeline?limit=2`).set("Cookie", logged.cookie); const second = await request(app).get(`/api/v1/cases/${legalCase.id}/timeline?limit=2&cursor=${encodeURIComponent(first.body.meta.nextCursor)}`).set("Cookie", logged.cookie); expect(first.body.data).toHaveLength(2); expect(second.body.data).toHaveLength(1); expect(new Set([...first.body.data, ...second.body.data].map((item: { id: string }) => item.id)).size).toBe(3); });
  it("validates presentation dates before persisting", async () => { const logged = await auth(); const legalCase = await createSyntheticCase(testPrisma, logged.user); const response = await request(buildApp()).post(`/api/v1/cases/${legalCase.id}/actions`).set(headers(logged)).send({ type: "FILING", title: "Fechas inválidas", documentAt: "2026-03-02T10:00:00.000Z", presentationAt: "2026-03-01T10:00:00.000Z" }); expect(response.status).toBe(400); expect(await testPrisma.caseAction.count()).toBe(0); });
});
