import request from "supertest"; import { afterAll, beforeEach, describe, expect, it } from "vitest"; import { buildApp } from "../../src/app.js"; import { disconnectDatabase } from "../../src/database/prisma.js"; import { passwordService } from "../../src/modules/auth/password.service.js"; import { NotificationWorker } from "../../src/workers/notification-worker.js"; import { resetTestDatabase, testPrisma } from "../helpers/database.js";
const ORIGIN = "http://localhost:3000"; const PASSWORD = "ClaveSegura123";
async function auth(codes: string[], suffix: string) { const permissions = await Promise.all(codes.map((code) => testPrisma.permission.upsert({ where: { code }, update: {}, create: { code, description: code } }))); const role = await testPrisma.role.create({ data: { code: `N_${suffix.toUpperCase()}`, name: suffix, permissions: { create: permissions.map(({ id }) => ({ permissionId: id })) } } }); const user = await testPrisma.user.create({ data: { email: `${suffix}@example.com`, emailNormalized: `${suffix}@example.com`, name: suffix, passwordHash: await passwordService.hash(PASSWORD), roleId: role.id } }); const response = await request(buildApp()).post("/api/v1/auth/login").set("Origin", ORIGIN).send({ email: user.email, password: PASSWORD }); const cookies = response.headers["set-cookie"] as unknown as string[]; return { user, cookie: cookies[0]!.split(";")[0]!, csrf: response.body.data.csrfToken as string }; }
const headers = (value: { cookie: string; csrf: string }) => ({ Origin: ORIGIN, Cookie: value.cookie, "x-csrf-token": value.csrf }); beforeEach(resetTestDatabase); afterAll(async () => { await testPrisma.$disconnect(); await disconnectDatabase(); });

describe("notifications, general worker and feedback", () => {
  it("lets two workers claim an assignment once and keeps processing idempotent", async () => { const owner = await auth([], "owner"); const task = await testPrisma.task.create({ data: { title: "Notificar asignación", createdById: owner.user.id } }); const event = await testPrisma.outboxEvent.create({ data: { type: "TASK_ASSIGNED", aggregateType: "Task", aggregateId: task.id, payload: { taskId: task.id, userId: owner.user.id } } }); const results = await Promise.all([new NotificationWorker(testPrisma).runOnce(), new NotificationWorker(testPrisma).runOnce()]); expect(results.filter(Boolean)).toHaveLength(1); expect(await testPrisma.notification.count()).toBe(1); expect((await testPrisma.notification.findFirstOrThrow()).dedupeKey).toBe(`${event.id}:${owner.user.id}`); expect(await new NotificationWorker(testPrisma).runOnce()).toBe(false); expect(await testPrisma.notification.count()).toBe(1); });

  it("respects preferences and schedules each due notification only once", async () => { const owner = await auth([], "preferences"); const app = buildApp(); const saved = await request(app).patch("/api/v1/notification-preferences").set(headers(owner)).send({ taskAssigned: false, dueSoonLeadDays: 2 }); expect(saved.status).toBe(200); expect(saved.body.data).toMatchObject({ taskAssigned: false, dueSoonLeadDays: 2 }); const task = await testPrisma.task.create({ data: { title: "Próxima", dueDate: new Date(Date.now() + 86_400_000), createdById: owner.user.id, assignments: { create: { userId: owner.user.id, assignedById: owner.user.id } } } }); await testPrisma.outboxEvent.create({ data: { type: "TASK_ASSIGNED", aggregateType: "Task", aggregateId: task.id, payload: { taskId: task.id, userId: owner.user.id } } }); const worker = new NotificationWorker(testPrisma); await worker.runOnce(); expect(await testPrisma.notification.count()).toBe(0); await worker.enqueueTaskDeadlines(); await worker.enqueueTaskDeadlines(); expect(await testPrisma.outboxEvent.count({ where: { type: "TASK_DUE_SOON" } })).toBe(1); await worker.runOnce(); expect((await testPrisma.notification.findFirstOrThrow()).type).toBe("TASK_DUE_SOON"); });

  it("isolates each inbox and forbids reading another user's notification", async () => { const first = await auth([], "inboxfirst"); const second = await auth([], "inboxsecond"); const notification = await testPrisma.notification.create({ data: { dedupeKey: "inbox:first", userId: first.user.id, type: "TEST", title: "Privada" } }); const app = buildApp(); const secondList = await request(app).get("/api/v1/notifications").set("Cookie", second.cookie); expect(secondList.body.data).toEqual([]); expect((await request(app).post(`/api/v1/notifications/${notification.id}/read`).set(headers(second))).status).toBe(404); expect((await request(app).post(`/api/v1/notifications/${notification.id}/read`).set(headers(first))).status).toBe(204); expect((await request(app).get("/api/v1/notifications?unread=true").set("Cookie", first.cookie)).body.meta.unreadCount).toBe(0); });

  it("creates feedback for every user and restricts resolution to managers", async () => { const author = await auth(["feedback.create"], "feedbackauthor"); const manager = await auth(["feedback.create", "feedback.manage"], "feedbackmanager"); const app = buildApp(); const created = await request(app).post("/api/v1/feedback").set(headers(author)).send({ message: "Agregar exportación del listado" }); expect(created.status).toBe(201); expect((await request(app).get("/api/v1/feedback").set("Cookie", author.cookie)).status).toBe(403); const list = await request(app).get("/api/v1/feedback?status=OPEN").set("Cookie", manager.cookie); expect(list.body.data).toHaveLength(1); const resolved = await request(app).patch(`/api/v1/feedback/${created.body.data.id}`).set(headers(manager)).send({ status: "RESOLVED", resolution: "Incluido en roadmap" }); expect(resolved.status).toBe(200); expect(resolved.body.data).toMatchObject({ status: "RESOLVED", resolution: "Incluido en roadmap" }); expect(resolved.body.data.resolvedBy.id).toBe(manager.user.id); });

  it("moves terminal failures to FAILED and alerts audit administrators", async () => { const admin = await auth(["audit.read"], "workeradmin"); const event = await testPrisma.outboxEvent.create({ data: { type: "TASK_ASSIGNED", payload: {}, attempts: 4 } }); expect(await new NotificationWorker(testPrisma).runOnce()).toBe(true); expect((await testPrisma.outboxEvent.findUniqueOrThrow({ where: { id: event.id } })).status).toBe("FAILED"); const alert = await testPrisma.notification.findFirstOrThrow({ where: { userId: admin.user.id } }); expect(alert.type).toBe("WORKER_EVENT_FAILED"); });

  it("exposes filtered immutable audit only to the audit permission", async () => { const admin = await auth(["audit.read"], "auditreader"); const regular = await auth([], "auditdenied"); await testPrisma.auditLog.create({ data: { actorId: admin.user.id, action: "SECURITY_REVIEW", entityType: "System", metadata: { safe: true } } }); const app = buildApp(); expect((await request(app).get("/api/v1/audit-logs").set("Cookie", regular.cookie)).status).toBe(403); const response = await request(app).get("/api/v1/audit-logs?entityType=System&limit=1").set("Cookie", admin.cookie); expect(response.status).toBe(200); expect(response.body.data[0]).toMatchObject({ action: "SECURITY_REVIEW", entityType: "System", actor: { id: admin.user.id } }); expect(response.body.data[0].id).toBeTypeOf("string"); });
});
